# Generated by Django 4.0.4 on 2022-05-10 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id_vacuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('num_run', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50, null=True)),
                ('appellidos', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=30, null=True)),
                ('clave', models.CharField(max_length=128, null=True)),
                ('nombre_usr', models.CharField(max_length=20, null=True)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntos.tipo_usuario')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DireccionU',
            fields=[
                ('id_direccionu', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntos.comuna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionC',
            fields=[
                ('id_direccionc', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntos.centro')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntos.comuna')),
            ],
        ),
    ]
