# Generated by Django 4.0.5 on 2022-06-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='descripcion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='lab',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
