# Generated by Django 4.0.5 on 2022-06-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0005_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='ubicacion',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
