# Generated by Django 4.0.5 on 2022-06-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0008_centro_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='lat',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='centro',
            name='lng',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
