# Generated by Django 4.0.5 on 2022-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0009_centro_lat_centro_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='foto',
            field=models.ImageField(null=True, upload_to='puntos'),
        ),
    ]
