# Generated by Django 4.0.5 on 2022-06-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0010_alter_centro_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vac_cen',
            fields=[
                ('id_vac_cen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntos.centro')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puntos.vacuna')),
            ],
        ),
    ]
