# Generated by Django 4.0.5 on 2022-06-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0011_vac_cen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_p',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
